---
- hosts: all
  gather_facts: no
  tasks:
    - name: debug
      debug:
        msg: "branch1"

    - name: get current https stats
      community.general.nginx_status_info:
        url: https://localhost/nginx_status
      register: result

    - name: debug
      debug:
        var: result
